stages:
  
  
  download_data:
    cmd: python .\src\data\data_download.py
    deps:
    - .\src\data\data_download.py
    outs:
    - .\data\initial_data\initial_data.csv
    - .\data\initial_data\target.csv
  
  
  prepocess_data:
    cmd: python .\src\data\data_prepare.py
    deps:
    - .\data\initial_data\initial_data.csv
    - .\src\data\data_prepare.py
    outs:
    - .\data\prepared_data\prepared_data.csv
  
  
  tuning:
    cmd: python .\src\train\tuning.py --config params.yaml
    deps:
    - .\data\initial_data\target.csv
    - .\data\prepared_data\prepared_data.csv
    - .\src\train\tuning.py
    params:
    - tuning.n_trials
    - tuning.seed
    - tuning.val_size
    outs:
    - .\configs\best_params.json
  
  
  training:
    cmd: python .\src\train\training.py --config params.yaml
    deps:
    - .\data\initial_data\target.csv
    - .\data\prepared_data\prepared_data.csv
    - .\configs\best_params.json
    - .\src\train\training.py
    params:
    - prepare.random_state
    - prepare.test_size
    - train.seed
    - train.test_size
    - train.val_size
    outs:
    - .\models\best_model.pkl
    metrics:
    - metrics\metrics.json:
        cache: false
